from pymongo import MongoClient
from bson.decimal128 import Decimal128
from datetime import datetime, timedelta

client = MongoClient("mongodb://localhost:***@equivale.com",
     "description": "Cachecol feito a mao com fio de algodao organico. Padrao exclusivo em tons terrosos.",
     "category": "Artesanato", "priceInEquivale": D("45"), "images": [],
     "status": 0, "createdAt": days_ago(20), "updatedAt": days_ago(20)},
    {"_id": "prod_02", "sellerId": "user_maria", "title": "Conjunto de Amigurumi - Familia de Ursos",
     "description": "Conjunto com 4 ursinhos de croche. Feito com fio acrilico premium, seguro para criancas.",
     "category": "Artesanato", "priceInEquivale": D("65"), "images": [],
     "status": 0, "createdAt": days_ago(15), "updatedAt": days_ago(15)},
    {"_id": "prod_03", "sellerId": "user_carlos", "title": "Kit Fotografico para Retrato em Casa",
     "description": "Guia completo + templates de iluminacao caseira para fotos de retrato profissional.",
     "category": "Fotografia", "priceInEquivale": D("30"), "images": [],
     "status": 0, "createdAt": days_ago(18), "updatedAt": days_ago(18)},
    {"_id": "prod_04", "sellerId": "user_carlos", "title": "Impressao Fine Art A3 - Paisagem Brasileira",
     "description": "Impressao em papel algodao 300g de paisagem capturada no litoral paulista. Edicao limitada, assinada.",
     "category": "Arte", "priceInEquivale": D("55"), "images": [],
     "status": 0, "createdAt": days_ago(12), "updatedAt": days_ago(12)},
    {"_id": "prod_05", "sellerId": "user_pedro", "title": "Banqueta de Madeira de Demolicao",
     "description": "Banqueta rustica feita com madeira reaproveitada de construcoes. Acabamento em oleo natural.",
     "category": "Madeira", "priceInEquivale": D("80"), "images": [],
     "status": 0, "createdAt": days_ago(10), "updatedAt": days_ago(10)},
    {"_id": "prod_06", "sellerId": "user_pedro", "title": "Estante Flutuante de Pallet",
     "description": "Estante feita com pallets tratados e lixados. Perfeita para livros e plantas. 1m x 0.60m.",
     "category": "Madeira", "priceInEquivale": D("95"), "images": [],
     "status": 0, "createdAt": days_ago(8), "updatedAt": days_ago(8)},
    {"_id": "prod_07", "sellerId": "user_ana", "title": "Kit de Temperos Artesanais - 5 Especiarias",
     "description": "Conjunto com paprica defumada, curcuma moida, pimenta dedo-de-moca, alecrim seco e mix de ervas finas.",
     "category": "Alimentacao", "priceInEquivale": D("25"), "images": [],
     "status": 0, "createdAt": days_ago(14), "updatedAt": days_ago(14)},
    {"_id": "prod_08", "sellerId": "user_ana", "title": "Geleia de Pimenta com Manga",
     "description": "Geleia artesanal de manga com pimenta biquinho. Perfeita para acompanhar queijos e carnes. Pote de 250g.",
     "category": "Alimentacao", "priceInEquivale": D("20"), "images": [],
     "status": 0, "createdAt": days_ago(7), "updatedAt": days_ago(7)},
    {"_id": "prod_09", "sellerId": "user_rafael", "title": "Muda de Orquidea Phalaenopsis",
     "description": "Muda saudavel de orquidea Phalaenopsis branca. Inclui substrato e guia de cuidados.",
     "category": "Jardinagem", "priceInEquivale": D("50"), "images": [],
     "status": 0, "createdAt": days_ago(16), "updatedAt": days_ago(16)},
    {"_id": "prod_10", "sellerId": "user_rafael", "title": "Kit de Suculentas Raras - 6 Variedades",
     "description": "Conjunto com 6 mudas de suculentas raras em vasinhos de barro. Inclui Echeveria, Haworthia, Lithops e mais.",
     "category": "Jardinagem", "priceInEquivale": D("35"), "images": [],
     "status": 0, "createdAt": days_ago(5), "updatedAt": days_ago(5)},
    {"_id": "prod_11", "sellerId": "user_julia", "title": "Pulseira de Sementes e Cordao Trancado",
     "description": "Pulseira feita com sementes de acai e cordao de algodao trancado a mao. Design boho.",
     "category": "Artesanato", "priceInEquivale": D("15"), "images": [],
     "status": 0, "createdAt": days_ago(11), "updatedAt": days_ago(11)},
    {"_id": "prod_12", "sellerId": "user_joao", "title": "Template de Portfolio para Devs",
     "description": "Template HTML/CSS/JS responsivo para portfolio de desenvolvedores. Inclui secoes de projetos, blog e contato.",
     "category": "Tecnologia", "priceInEquivale": D("40"), "images": [],
     "status": 0, "createdAt": days_ago(13), "updatedAt": days_ago(13)},
    {"_id": "prod_13", "sellerId": "user_lucia", "title": "Kit de Incensos Artesanais - 10 Unidades",
     "description": "Incensos feitos com ervas naturais e oleos essenciais. Aromas: lavanda, sandalo, alecrim, eucalipto e mais.",
     "category": "Bem-estar", "priceInEquivale": D("22"), "images": [],
     "status": 0, "createdAt": days_ago(9), "updatedAt": days_ago(9)},
    {"_id": "prod_14", "sellerId": "user_lucia", "title": "Vela Aromatica de Cera de Soja",
     "description": "Vela de cera de soja 100% natural com oleo essencial de laranja doce e canela. Duracao: ~40h.",
     "category": "Bem-estar", "priceInEquivale": D("28"), "images": [],
     "status": 0, "createdAt": days_ago(3), "updatedAt": days_ago(3)},
    {"_id": "prod_15", "sellerId": "user_carlos", "title": "Presets de Edicao de Fotos - Pack Natureza",
     "description": "15 presets para Lightroom com foco em paisagens e natureza brasileira. Tons quentes e vibrantes.",
     "category": "Fotografia", "priceInEquivale": D("20"), "images": [],
     "status": 0, "createdAt": days_ago(2), "updatedAt": days_ago(2)},
]
db.products.insert_many(products)
print(f"OK {len(products)} products")

# SERVICES (12)
services = [
    {"_id": "serv_01", "providerId": "user_joao", "title": "Aula Particular de JavaScript/TypeScript",
     "description": "Aula de 1h para iniciantes ou intermediarios. Aprendemos na pratica: criamos um mini-projeto real juntos.",
     "category": "Educacao", "priceInEquivale": D("35"),
     "duration": timedelta(hours=1), "location": "Online (Google Meet)",
     "status": 0, "createdAt": days_ago(25), "updatedAt": days_ago(25)},
    {"_id": "serv_02", "providerId": "user_joao", "title": "Review e Refatoracao de Codigo",
     "description": "Envie seu codigo que eu analiso, dou feedback detalhado e sugiro melhorias de performance e boas praticas.",
     "category": "Tecnologia", "priceInEquivale": D("50"),
     "duration": timedelta(hours=2), "location": "Online (assincrono)",
     "status": 0, "createdAt": days_ago(18), "updatedAt": days_ago(18)},
    {"_id": "serv_03", "providerId": "user_ana", "title": "Montagem de Cardapio Semanal Vegano",
     "description": "Monto um cardapio completo de 7 dias com receitas, lista de compras e dicas de preparo. 100% vegano.",
     "category": "Culinaria", "priceInEquivale": D("40"),
     "duration": timedelta(minutes=30), "location": "Online",
     "status": 0, "createdAt": days_ago(20), "updatedAt": days_ago(20)},
    {"_id": "serv_04", "providerId": "user_ana", "title": "Aula de Culinaria - Massa Fresca",
     "description": "Aula de 2h aprendendo a fazer massa fresca (pasta, nhoque e ravioli) do zero. Inclui lista de ingredientes.",
     "category": "Culinaria", "priceInEquivale": D("55"),
     "duration": timedelta(hours=2), "location": "Presencial - Sao Paulo (Zona Sul)",
     "status": 0, "createdAt": days_ago(12), "updatedAt": days_ago(12)},
    {"_id": "serv_05", "providerId": "user_carlos", "title": "Ensaio Fotografico Profissional",
     "description": "Ensaio de 1h em estudio ou local externo. Inclui 15 fotos editadas em alta resolucao.",
     "category": "Fotografia", "priceInEquivale": D("100"),
     "duration": timedelta(hours=1), "location": "Sao Paulo capital ou online",
     "status": 0, "createdAt": days_ago(15), "updatedAt": days_ago(15)},
    {"_id": "serv_06", "providerId": "user_carlos", "title": "Design de Logo para Seu Projeto",
     "description": "Crio 3 opcoes de logo para seu projeto/negocio. Inclui revisoes e entrega em PNG, SVG e PDF.",
     "category": "Design", "priceInEquivale": D("75"),
     "duration": timedelta(hours=3), "location": "Online",
     "status": 0, "createdAt": days_ago(8), "updatedAt": days_ago(8)},
    {"_id": "serv_07", "providerId": "user_lucia", "title": "Sessao de Yoga e Meditacao",
     "description": "Sessao de 1h combinando tecnicas de Hatha Yoga e meditacao guiada. Adapta para todos os niveis.",
     "category": "Saude", "priceInEquivale": D("30"),
     "duration": timedelta(hours=1), "location": "Online (Zoom) ou presencial",
     "status": 0, "createdAt": days_ago(22), "updatedAt": days_ago(22)},
    {"_id": "serv_08", "providerId": "user_lucia", "title": "Consultoria de Bem-Estar e Habitos",
     "description": "Avaliacao dos seus habitos diarios e plano personalizado de rotina saudavel. Inclui acompanhamento por 2 semanas.",
     "category": "Saude", "priceInEquivale": D("60"),
     "duration": timedelta(hours=1, minutes=30), "location": "Online",
     "status": 0, "createdAt": days_ago(10), "updatedAt": days_ago(10)},
    {"_id": "serv_09", "providerId": "user_pedro", "title": "Restauracao de Movel Antigo",
     "description": "Avaliacao + restauracao de 1 movel pequeno (cadeira, mesa lateral, criado-mudo). Lixamento, pintura e acabamento.",
     "category": "Madeira", "priceInEquivale": D("90"),
     "duration": timedelta(hours=5), "location": "Atendimento em domicilio - Sao Paulo",
     "status": 0, "createdAt": days_ago(17), "updatedAt": days_ago(17)},
    {"_id": "serv_10", "providerId": "user_julia", "title": "Aula de Violao para Iniciantes",
     "description": "Aula de 1h para quem nunca tocou violao. Aprenda acordes basicos e sua primeira musica.",
     "category": "Musica", "priceInEquivale": D("25"),
     "duration": timedelta(hours=1), "location": "Online ou presencial - SP",
     "status": 0, "createdAt": days_ago(14), "updatedAt": days_ago(14)},
    {"_id": "serv_11", "providerId": "user_julia", "title": "Seresta Personalizada - 3 Musicas",
     "description": "Gravo 3 musicas de sua escolha em violao e voz, com video de alta qualidade para presentear alguem.",
     "category": "Musica", "priceInEquivale": D("70"),
     "duration": timedelta(hours=2), "location": "Online",
     "status": 0, "createdAt": days_ago(6), "updatedAt": days_ago(6)},
    {"_id": "serv_12", "providerId": "user_rafael", "title": "Projeto de Jardim Pequeno",
     "description": "Elaboro um projeto completo para jardim de ate 20m2: plantas ideais, disposicao, substrato e cronograma de plantio.",
     "category": "Jardinagem", "priceInEquivale": D("45"),
     "duration": timedelta(hours=1), "location": "Online com visita opcional",
     "status": 0, "createdAt": days_ago(9), "updatedAt": days_ago(9)},
]
db.services.insert_many(services)
print(f"OK {len(services)} services")

# COMMUNITIES (6)
communities = [
    {"_id": "comm_01", "name": "Artesaos do Brasil",
     "description": "Comunidade para quem faz artesanato: croche, trico, patchwork, ceramica e muito mais.",
     "bannerUrl": None, "creatorId": "user_maria",
     "members": ["user_maria", "user_ana", "user_julia", "user_lucia", "user_rafael"],
     "createdAt": days_ago(50), "updatedAt": days_ago(5)},
    {"_id": "comm_02", "name": "Dev Exchange",
     "description": "Desenvolvedores trocando conhecimento e servicos. Codigo review, pair programming, mentorias.",
     "bannerUrl": None, "creatorId": "user_joao",
     "members": ["user_joao", "user_carlos", "user_pedro"],
     "createdAt": days_ago(40), "updatedAt": days_ago(3)},
    {"_id": "comm_03", "name": "Cozinha Colaborativa",
     "description": "Receitas, dicas de culinaria e troca de alimentos artesanais. Veganos e onivoros todos bem-vindos!",
     "bannerUrl": None, "creatorId": "user_ana",
     "members": ["user_ana", "user_maria", "user_joao", "user_carlos", "user_julia", "user_pedro", "user_rafael"],
     "createdAt": days_ago(35), "updatedAt": days_ago(2)},
    {"_id": "comm_04", "name": "Bem-Estar e Mindfulness",
     "description": "Espaco para compartilhar praticas de yoga, meditacao, alimentacao saudavel e cuidados com a mente e corpo.",
     "bannerUrl": None, "creatorId": "user_lucia",
     "members": ["user_lucia", "user_ana", "user_julia", "user_maria"],
     "createdAt": days_ago(30), "updatedAt": days_ago(7)},
    {"_id": "comm_05", "name": "Mao na Massa - Marcenaria",
     "description": "Para marceneiros, carpinteiros e entusiastas de madeira. Projetos DIY, tecnicas e troca de servicos.",
     "bannerUrl": None, "creatorId": "user_pedro",
     "members": ["user_pedro", "user_joao", "user_rafael"],
     "createdAt": days_ago(25), "updatedAt": days_ago(10)},
    {"_id": "comm_06", "name": "Musicos Independentes",
     "description": "Conectando musicos para colaboracoes, jams e troca de servicos. Violao, canto, producao musical e mais.",
     "bannerUrl": None, "creatorId": "user_julia",
     "members": ["user_julia", "user_carlos", "user_lucia", "user_ana"],
     "createdAt": days_ago(15), "updatedAt": days_ago(1)},
]
db.communities.insert_many(communities)
print(f"OK {len(communities)} communities")

# TRANSACTIONS (10)
transactions = [
    {"_id": "txn_01", "fromUserId": "user_joao", "toUserId": "user_maria", "amount": D("45"),
     "description": "Compra: Cachecol de Croche Artesanal", "transactionType": 0,
     "relatedItemId": "prod_01", "createdAt": days_ago(18)},
    {"_id": "txn_02", "fromUserId": "user_carlos", "toUserId": "user_joao", "amount": D("50"),
     "description": "Compra: Review e Refatoracao de Codigo", "transactionType": 0,
     "relatedItemId": "serv_02", "createdAt": days_ago(16)},
    {"_id": "txn_03", "fromUserId": "user_maria", "toUserId": "user_lucia", "amount": D("30"),
     "description": "Compra: Sessao de Yoga e Meditacao", "transactionType": 0,
     "relatedItemId": "serv_07", "createdAt": days_ago(14)},
    {"_id": "txn_04", "fromUserId": "user_ana", "toUserId": "user_pedro", "amount": D("90"),
     "description": "Compra: Restauracao de Movel Antigo", "transactionType": 0,
     "relatedItemId": "serv_09", "createdAt": days_ago(12)},
    {"_id": "txn_05", "fromUserId": "user_julia", "toUserId": "user_ana", "amount": D("40"),
     "description": "Compra: Cardapio Semanal Vegano", "transactionType": 0,
     "relatedItemId": "serv_03", "createdAt": days_ago(10)},
    {"_id": "txn_06", "fromUserId": "user_rafael", "toUserId": "user_carlos", "amount": D("100"),
     "description": "Compra: Ensaio Fotografico Profissional", "transactionType": 0,
     "relatedItemId": "serv_05", "createdAt": days_ago(8)},
    {"_id": "txn_07", "fromUserId": "user_pedro", "toUserId": "user_rafael", "amount": D("50"),
     "description": "Compra: Muda de Orquidea Phalaenopsis", "transactionType": 0,
     "relatedItemId": "prod_09", "createdAt": days_ago(6)},
    {"_id": "txn_08", "fromUserId": "user_admin", "toUserId": "user_joao", "amount": D("100"),
     "description": "Bonus de boas-vindas", "transactionType": 2,
     "relatedItemId": None, "createdAt": days_ago(55)},
    {"_id": "txn_09", "fromUserId": "user_admin", "toUserId": "user_maria", "amount": D("100"),
     "description": "Bonus de boas-vindas", "transactionType": 2,
     "relatedItemId": None, "createdAt": days_ago(60)},
    {"_id": "txn_10", "fromUserId": "user_joao", "toUserId": "user_julia", "amount": D("25"),
     "description": "Transferencia: ajuda com aulas", "transactionType": 1,
     "relatedItemId": None, "createdAt": days_ago(4)},
]
db.transactions.insert_many(transactions)
print(f"OK {len(transactions)} transactions")

# REVIEWS (10)
reviews = [
    {"_id": "rev_01", "reviewerId": "user_joao", "targetUserId": "user_maria",
     "itemId": "prod_01", "itemType": "Product", "rating": 5,
     "comment": "Cachecol lindo! A Maria foi super atenciosa e a qualidade do trabalho e incrivel.",
     "createdAt": days_ago(17)},
    {"_id": "rev_02", "reviewerId": "user_carlos", "targetUserId": "user_joao",
     "itemId": "serv_02", "itemType": "Service", "rating": 5,
     "comment": "Excelente review de codigo! O Joao identificou bugs que eu nao tinha percebido.",
     "createdAt": days_ago(15)},
    {"_id": "rev_03", "reviewerId": "user_maria", "targetUserId": "user_lucia",
     "itemId": "serv_07", "itemType": "Service", "rating": 4,
     "comment": "Sessao muito relaxante. Me senti renovada! So acho que poderia ter mais variacoes de postura.",
     "createdAt": days_ago(13)},
    {"_id": "rev_04", "reviewerId": "user_ana", "targetUserId": "user_pedro",
     "itemId": "serv_09", "itemType": "Service", "rating": 5,
     "comment": "Pedro e um artesao! Restaurou minha cadeira de forma que ficou melhor que o original.",
     "createdAt": days_ago(11)},
    {"_id": "rev_05", "reviewerId": "user_julia", "targetUserId": "user_ana",
     "itemId": "serv_03", "itemType": "Service", "rating": 5,
     "comment": "Cardapio incrivel! As receitas sao faceis de seguir e muito saborosas.",
     "createdAt": days_ago(9)},
    {"_id": "rev_06", "reviewerId": "user_rafael", "targetUserId": "user_carlos",
     "itemId": "serv_05", "itemType": "Service", "rating": 5,
     "comment": "Melhor ensaio que ja fiz! Carlos tem um olhar unico e as fotos ficaram profissionais.",
     "createdAt": days_ago(7)},
    {"_id": "rev_07", "reviewerId": "user_pedro", "targetUserId": "user_rafael",
     "itemId": "prod_09", "itemType": "Product", "rating": 4,
     "comment": "Orquidea chegou saudavel e bem embalada. So demorou um pouco mais do que o esperado.",
     "createdAt": days_ago(5)},
    {"_id": "rev_08", "reviewerId": "user_joao", "targetUserId": "user_julia",
     "itemId": "serv_10", "itemType": "Service", "rating": 4,
     "comment": "Julia e paciente e didatica. Em uma aula ja consegui tocar minha primeira musica completa!",
     "createdAt": days_ago(13)},
    {"_id": "rev_09", "reviewerId": "user_lucia", "targetUserId": "user_ana",
     "itemId": "prod_08", "itemType": "Product", "rating": 5,
     "comment": "Geleia deliciosa! O equilibrio entre doce e picante e perfeito.",
     "createdAt": days_ago(6)},
    {"_id": "rev_10", "reviewerId": "user_carlos", "targetUserId": "user_pedro",
     "itemId": "prod_06", "itemType": "Product", "rating": 5,
     "comment": "Estante ficou linda! Acabamento impecavel e o Pedro ajudou a instalar. Recomendo demais.",
     "createdAt": days_ago(3)},
]
db.reviews.insert_many(reviews)
print(f"OK {len(reviews)} reviews")

# SUMMARY
print("\n=== SEED COMPLETE ===")
for col_name in ["users", "products", "services", "communities", "transactions", "reviews"]:
    print(f"  {col_name}: {db[col_name].count_documents({})}")
print("====================")
